Terracotta-OSS/tc-passthrough-testing

entity-test-lib/src/main/java/org/terracotta/entity/PassthroughStripe.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServer.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java, pom.xml
-this required renaming all instances of ServerEntityService to EntityServerService
=> Updated APIs version to 1.0.3.beta

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughInvocationBuilder.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServer.java
Also fixed an issue which could cause connections to incorrectly be given the same ID
=> Replicate messages, by default

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughConnection.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServiceRegistry.java
These are just some small bug fixes and extra diagnostics.
=> Small changes

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughMonitoringProducer.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServer.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java, pom.xml
This commit is just temporary.  It will need to be fixed up once #24 merges (since this includes those changes) and then again once the API change is released.
For now, this is just for sharing the branch more easily.
=> (READY) Sharing IStripeMonitoring implementation

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughMonitoringProducer.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
-no need to define a new class to just pass around a class instance
=> Switch to the common BasicServiceConfiguration for simple service configurations

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java, pom.xml
Add execution strategy to passthrough 
Fix reconfigure to new API
=> [DO NOT MERGE] Entity API changes

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughTestHelpers.java
-this name isn't chosen for any specific reason other than being unique within the stripe (which is all that should strictly be required)
Will self-merge.
=> Fix #38: Set a name for the new server

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughNullPlatformPersistentStorage.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughNullPlatformStorageServiceProvider.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
Changes related to the new persistence interface which can be merged prior to its release.
=> Pre persistence

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughEmulatedPersistentStorage.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughEmulatedStorageServiceProvider.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughLifeCycleHandler.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughNullPlatformPersistentStorage.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughNullPlatformStorageServiceProvider.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughTransactionOrderManager.java, pom.xml
-updates the deps
-includes support for IPlatformPersistence
-includes emulator for IPersistentStorage
-also changes the internal consumers of IPersistentStorage to IPlatformPersistence
Will self-merge, as discussed
=> Support for IPlatformPersistence

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServer.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServiceRegistry.java
This is an enhancement for service developers to test services under development that may override existing services in other jar files.
This change has been tested as well as build successfully on some of the dependent repos, by temporarily bumping up version numbers in these repos (e.g ehcache).
=> Fix #45: Enhancement to allow service provider overrides by user

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
-it is possible, through a very tight timing hole, for a call to IEntityMessenger to come in after the thread running the test has asked the server to shut-down
-in this case, we will drop the message on the ground since the effect we are trying to simulate is an unexpected crash of the server and this is the closest anologue
=> (READY TO MERGE) Handle IEntityMessenger call during shutdown

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughMessengerService.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughMessengerServiceProvider.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServer.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughTimerThread.java, pom.xml
This needs to be updated to the correct release version, prior to merge, once the upstream release is available.
=> (READY) Timer messenger support

entity-test-lib/src/main/java/org/terracotta/entity/PassthroughStripe.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughEmulatedStorageServiceProvider.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughNullPlatformStorageServiceProvider.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServer.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java, pom.xml
Support for API changes in the platform
Support loadExisting change
Support extended service objects addition
Support name change for ServiceProvider clear
=> tc-api changes

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughPlatformConfiguration.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServer.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
This addresses a few issues pointed out by the recent config changes and adds support for explicitly registering config objects.
=> Config suport

passthrough-server/src/main/java/org/terracotta/passthrough/IAsynchronousServerCrasher.java, passthrough-server/src/main/java/org/terracotta/passthrough/IMessageSenderWrapper.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughClusterControl.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughEntityRef.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughInterserverInterlock.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServer.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerCrasher.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerMessageDecoder.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java, pom.xml
Also adds support for the new EntityAPI exceptions.
Can only merge after API is released.
=> (DO NOT MERGE) Support consensus model

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughConnection.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughEntityRef.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServer.java, pom.xml
Depends on terracotta-apis being released after this change:  https://github.com/Terracotta-OSS/terracotta-apis/pull/211
=> Updated to account for changes to the API fetchEntity()

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughMessengerService.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
The RetirementManager in passthrough was not wired in correctly,
Clifford and I fixed that.
=> Fix for retirement manager in passthrough

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServer.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServiceRegistry.java
Fixes Issue 113 (Incorrect addition of default ServiceProviders):
https://github.com/Terracotta-OSS/tc-passthrough-testing/issues/113
=> No default ServiceProvider when one is configured

entity-test-lib/src/main/java/org/terracotta/entity/PassthroughEndpoint.java, entity-test-lib/src/main/java/org/terracotta/entity/PassthroughStripe.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughConnection.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughEntityClientEndpoint.java, pom.xml
Add support for added EntityClientEndpoint.release
=> Bump to latest Terracotta versions

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
=> Fix npe with concurrency strategy

entity-test-lib/src/main/java/org/terracotta/entity/PassThroughEntityActiveInvokeChannel.java, entity-test-lib/src/main/java/org/terracotta/entity/PassThroughEntityActiveInvokeContext.java, entity-test-lib/src/main/java/org/terracotta/entity/PassthroughEndpoint.java, entity-test-lib/src/main/java/org/terracotta/entity/PassthroughStripe.java, passthrough-server/src/main/java/org/terracotta/passthrough/IMessageSenderWrapper.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassThroughServerActiveInvokeContext.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughCommunicatorService.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughConnection.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughConnectionState.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughInterserverInterlock.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughInvocationBuilder.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughMessage.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughMessageCodec.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughMessengerService.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughMessengerServiceProvider.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughMonitor.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughRetirementManager.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerMessageDecoder.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughWait.java, passthrough-server/src/test/java/org/terracotta/passthrough/PassthroughConnectionStateTest.java, pom.xml
reconnect API
ActiveInvokeChannel
=> New tc-apis implementations

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughClusterControl.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughPlatformService.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughPlatformServiceProvider.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServer.java, pom.xml
=> Implement new platform service extensions

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerMessageDecoder.java, passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
make the message queue a real queue so that server synchronization does not interfere with the synchronization of the entity.
=> Fix #188 -  Rework server messaging

passthrough-server/src/main/java/org/terracotta/passthrough/PassthroughServerProcess.java
better locking for resend mode.
=> Fix #188 - Try #2
